### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#125] opened 2017-03-02 11:15 UTC
I set up Arachni to test the scheduling on the web ui. Initially I had the default installation with sqllite. I started a scan  and then scheduled it to rerun every hour. The next day I came  back to a 6 gig production.sqlite3. It seems to have tried to rerun the scan every second and The web interface has over 100o notifications.

I decided that I must have initialized the schedule incorrectly. I then reinstalled and configured with PostgreSQL. I ran the same scan and scheduled it to repeat every 6 hours starting after a scan ended. I returned to find hundreds of notifications and a 2 gig database.

My best guess is that the scheduler is erroneously creating scans in a shorter time frame.

**Comment by Zapotek** [comment] 2017-03-09 16:21
I can't reproduce the issue, can you please take a screenshot of the schedule configuration you used?

**Comment by bgerardw** [comment] 2017-03-09 16:42
I will try and reproduce it tomorrow and send you details. I have scans running and the last time I did it it looked up my machine so I will wait for them to complete.

**Comment by Zapotek** [comment] 2017-03-24 12:36
Ok, closing it for now then.

**Closed by Zapotek** 2017-03-24 12:36 UTC
Labels: bug
